# goal
string  sender_node   # sender node name 
string  text          # text to read
string  voice          # voice to speak with
uint8    priority     # priority of text
bool    debug         # debug message
---
# result
int32 msg_id          # id of queued message
uint8 IMPORTANT     = 1
uint8 MESSAGE       = 2
uint8 TEXT          = 3
uint8 NOTIFICATION  = 4
uint8 PROGRESS      = 5
---
# feedback
int32 msg_id          # id of queued message
uint8 msg_status      # status of queued message
string msg            # msg to say
uint8 SPD_BEGIN       = 1
uint8 SPD_END         = 2
uint8 SPD_INDEX_MARKS = 3
uint8 SPD_CANCEL      = 4
uint8 SPD_PAUSE       = 5
uint8 SPD_RESUME      = 6
