# goal
string  sender_node   # sender node name 
string  text          # text to read
string  voice          # voice to speak with
uint8    priority     # priority of text
---
# result
uint8 success         # result of reading text (not used in current version) 
---
# feedback
string message        # feedback of operation (not used in current version)
